### ISSUE TITLE
Config will not work

### ISSUE THREAD

**Issue by tintcar** [BananaPuncher714/LethalQuantities#35] opened 2024-01-18 03:31 UTC
i was customizing the amount of loot that would spawn keep in mind this has worked before but now it will not spawn anything even with saving and launching with modded version

**Comment by BananaPuncher714** [comment] 2024-01-18 04:02
You have to enable the scrap config for that particular moon in the `LethalQuantities/Global/Configuration.cfg` file. You can delete any configs that you are not using to cut down on the amount of files that show up.

**Comment by tintcar** [comment] 2024-01-18 04:39
Alright did that now im having a new problem. when ever i go onto a map for example vow, it just keeps me on a waiting for crew screen

**Comment by BananaPuncher714** [comment] 2024-01-18 04:51
Can you provide a profile code, and what are the errors in the console, if there are any?

**Comment by tintcar** [comment] 2024-01-18 05:15
sure
[Error  : Unity Log] ArgumentException: An item with the same key has already been added. Key: BottleBin (Item)
Stack trace:
System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) (at <787acc3c9a4c471ba7d971300105af24>:IL_015A)
System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) (at <787acc3c9a4c471ba7d971300105af24>:IL_0000)
LethalQuantities.Patches.RoundManagerPatch.onLoadNewLevelPrefix (RoundManager __instance, SelectableLevel& newLevel) (at <223bad60ee114d889151ca750c087f5b>:IL_04A1)
(wrapper dynamic-method) RoundManager.DMD<RoundManager::LoadNewLevel>(RoundManager,int,SelectableLevel)
StartOfRound+<OpenShipDoors>d__245.MoveNext () (at <af9b1eec498a45aebd42601d6ab85015>:IL_007F)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <e27997765c1848b09d8073e5d642717a>:IL_0026)

**Comment by BananaPuncher714** [comment] 2024-01-18 05:54
This is a duplicate of #30, which will be fixed next update.

**Comment by tintcar** [comment] 2024-01-18 14:01
Alright great! is there an time estimate for the next update?

**Comment by BananaPuncher714** [comment] 2024-01-18 19:35
Yes, once I fix #33 and am able to implement better comments for each option I will release a new update, which is hopefully tomorrow at the latest.

**Comment by tintcar** [comment] 2024-01-18 21:19
great thanks for the help 👍

**Closed** 2024-01-18 23:05 UTC
Labels: bug
