### ISSUE TITLE
the curve doesnt save in the config

### ISSUE THREAD

**Issue by Mickael46999** [BananaPuncher714/LethalQuantities#15] opened 2023-12-24 15:39 UTC

**Comment by BananaPuncher714** [comment] 2023-12-24 19:15
What is the curve you are trying to save? Can you provide your config files? Are you properly saving the file?

**Comment by Mickael46999** [comment] 2023-12-24 19:23
> What is the curve you are trying to save? Can you provide your config files? Are you properly saving the file?

Im doing like this: 0:4, 0.3:2, 0.5:5
And changing the . For , dont Work and the game change it to the base curve

**Comment by BananaPuncher714** [comment] 2023-12-24 19:43
Can you provide your entire config file? Here is an example curve that I am using: `0:-2, 0.45:4, 0.7593884:5, 1:15`

**Comment by Mickael46999** [comment] 2023-12-25 14:22
enemies: 0:5, 3:3, 5:4, 8:6 (dont working)
daytime 0:3, 3:2, 5:2, 7:-10 (working, the game when i put 0.5 it change it to 5)
outside  7:4, 8:7, 9:10 (dont working)

**Comment by Mickael46999** [comment] 2023-12-25 17:12
the outside and enemies dont work

**Comment by BananaPuncher714** [comment] 2023-12-25 17:43
The maximum key for each curve is 1. Changing it to a value above 1 does not do anything.

**Comment by Mickael46999** [comment] 2023-12-25 17:52
yeah but with 0.7 or 0,7 dont work and the enemies have 0:5 and it doesnt work

**Comment by BananaPuncher714** [comment] 2023-12-25 23:02
It does not work with a comma, only a period. If enemies are not spawning, then you need to document that in the other ticket you opened, #16. Can you list the steps to reproduce the error where the config overwrites what values you have changed?

**Comment by BananaPuncher714** [comment] 2023-12-26 23:33
Closing since it seemed like you were not using the proper format for an animation curve.

**Comment by BananaPuncher714** [comment] 2024-01-07 21:08
It seems like the locale of your operating system would have caused an error when loading any animation curves in the config. The default format should now use a dot(.) for representing numbers, with a comma as a separator. It should have been fixed in the most recent version(1.0.14).

**Closed** 2024-01-12 02:10 UTC
Labels: question
