### ISSUE TITLE
Moons prices errors, not working

### ISSUE THREAD

**Issue by HamedAlmanthari** [BananaPuncher714/LethalQuantities#71] opened 2024-02-28 15:12 UTC
hi. i'm trying to use LQ to add custom entities to custom moons and also change the prices of moons but i'm getting some errors and some moons prices don't change while some of them change (i think). i'm using LLL and not using LE. here is the log:

[New Text Document.txt](https://github.com/BananaPuncher714/LethalQuantities/files/14435962/New.Text.Document.txt)

this is the jason file, not sure if it's configured correctly. i used "exported global" preset only.

[Presets.json](https://github.com/BananaPuncher714/LethalQuantities/files/14435948/Presets.json)

EDIT: this is the new jason file, still the same errors:

[Presets.json](https://github.com/BananaPuncher714/LethalQuantities/files/14437519/Presets.json)

EDIT 2: new preset after deleting and generating, still same errors:

[Presets.json](https://github.com/BananaPuncher714/LethalQuantities/files/14437857/Presets.json)

**Comment by HamedAlmanthari** [comment] 2024-02-28 15:36
also, if i put only the custom entities in global preset's enemies, and i don't enable enemies in the other presets, do only custom entities spawn in every moon and the vanilla ones don't? or the vanilla ones will use the default spawn weight of the moon and the custom ones will use weights from the parent preset? it would be appreciated if you could take a look at my preset and tell me if i used it wrong or smth. if you can't then it's understandable.

**Comment by HamedAlmanthari** [comment] 2024-02-28 15:48
after testing, nothing spawns except for the ones in the "exported global".

**Comment by HamedAlmanthari** [comment] 2024-02-28 16:47
i forgot to take a screenshot sorry.

![image](https://github.com/BananaPuncher714/LethalQuantities/assets/133137232/fbe315fc-5bfa-471c-8df9-cecc3dc469d1)

**Comment by HamedAlmanthari** [comment] 2024-02-28 16:48
i just realized something. i think there is a moon that does not appear on the preset file. it's EchoReach.

**Comment by HamedAlmanthari** [comment] 2024-02-28 16:55
i created a new json file and trying again

**Comment by HamedAlmanthari** [comment] 2024-02-28 17:04
echoreach still doesn't show up. are these issues from their end?

**Comment by BananaPuncher714** [comment] 2024-02-28 17:41
This is sort of an issue with their moon, it appears that Celestria and EchoReach share the same object name(TestAsset), so LethalQuantities considers them both the same moon. Ideally the moon creator would make them unique, like all the other moons(ExperimentationLevel, TriskelionSelectable, atlasabyss, 94 Polarus, etc)

**Comment by HamedAlmanthari** [comment] 2024-02-28 17:43
> This is sort of an issue with their moon, it appears that Celestria and EchoReach share the same object name(TestAsset), so LethalQuantities considers them both the same moon. Ideally the moon creator would make them unique, like all the other moons(ExperimentationLevel, TriskelionSelectable, atlasabyss, 94 Polarus, etc)

ah i see. what about the rest of the moons that don't change price?

**Comment by BananaPuncher714** [comment] 2024-02-28 17:48
Well, since it encountered an error, it stopped what it was doing, so any moons that come after EchoReach would not have been updated.

**Comment by HamedAlmanthari** [comment] 2024-02-28 17:49
> Well, since it encountered an error, it stopped what it was doing, so any moons that come after EchoReach would not have been updated.

oh so that's why. i don't even know what's the name of the mod that adds EchoReach and where to contact its creator 💀
i'll look into it. ty very much.

**Comment by HamedAlmanthari** [comment] 2024-02-28 18:14
i contacted the author of the mod and they said they're on it. is there a way to write an exception when such error happens to prevent the code from stopping after the error occurs and to log if there are multiple moons with the same object name? just to help anyone without this knowledge to solve or prevent this issue in the future.

**Comment by BananaPuncher714** [comment] 2024-02-28 18:54
I can try to add in something like that, but it is hard to tell if the error was caused by another error previously, or if it's a mistake on my part, or if another mod has changed something else that was unexpected, etc. There are generally too many points of failure to make it worthwhile, but for small edge cases, I've been trying to improve it.

**Comment by HamedAlmanthari** [comment] 2024-02-28 19:07
Oh so it’s not 100% because of the object names and the error might persist after changing them?

**Comment by BananaPuncher714** [comment] 2024-02-28 19:14
Yes, for example, if LethalQuantities somehow fails when trying to export/import data, then there would be no presets available, at which point it might throw an error when trying to fetch prices or something. The cause of no presets available could be one of many(non exhaustive):
- Failed to read the preset file
- Failed to write to disk
- Found an improperly formatted level
- Found an improperly formatted enemy type
- etc
It is slightly unrealistic to try and cover all the cases, and generally if there's an error anyways you probably don't want to continue(since it could entirely ruin your gameplay). The baseline for functionality though, is that the mod should work without error with the vanilla Lethal Company moons, enemies, items, etc.

**Comment by HamedAlmanthari** [comment] 2024-02-28 19:38
alright i think i understood a little 😂. i'll see if it fixes the issue and get back to you. if not then idk maybe just leave it lmao. ty tho

**Comment by HamedAlmanthari** [comment] 2024-02-28 19:55
is it normal that some moons show -1 price by default?

![image](https://github.com/BananaPuncher714/LethalQuantities/assets/133137232/7e7f59cd-9b58-4196-8985-f562e9815cc5)

**Comment by BananaPuncher714** [comment] 2024-02-28 20:09
No, that's a minor bug with LethalQuantities, where sometimes the price of a moon is updated after the price is checked, so it's -1 by default. It should have updated but sometimes it doesn't. I'll have this fixed next update.

**Comment by HamedAlmanthari** [comment] 2024-02-28 20:11
ok i regenerated the jason file and reconfigured the moons and enemies. i still get errors but the prices change. i'll just ignore them for now idk if they'll cause issues later on but you said i should probably not continue if i encouter an error so idk lmao.

[New Text Document.txt](https://github.com/BananaPuncher714/LethalQuantities/files/14439521/New.Text.Document.txt)
[Presets.json](https://github.com/BananaPuncher714/LethalQuantities/files/14439522/Presets.json)

before:
![Screenshot 2024-02-28 235947](https://github.com/BananaPuncher714/LethalQuantities/assets/133137232/47324ef9-30b9-4bd9-83dd-39cff359cb12)
after:
![Screenshot 2024-02-29 000641](https://github.com/BananaPuncher714/LethalQuantities/assets/133137232/633f84d9-3be3-4f6b-a5d6-e51ceb6e9dae)

**Comment by BananaPuncher714** [comment] 2024-02-28 20:25
Sorry, you can ignore those errors, they are from some legacy code with the old configuration system that I forgot to remove(will be fixed next update, too).

If a mod changes the object names, the Preset.json file will automatically update with the relevant default data, but you will have to go in and set the preset for the updated levels/objects, since they are considered different objects.

**Comment by HamedAlmanthari** [comment] 2024-02-28 20:26
> Sorry, you can ignore those errors, they are from some legacy code with the old configuration system that I forgot to remove(will be fixed next update, too).
> 
> If a mod changes the object names, the Preset.json file will automatically update with the relevant default data, but you will have to go in and set the preset for the updated levels/objects, since they are considered different objects.

alright thank youuu!

**Closed** 2024-03-02 01:09 UTC
Labels: bug
