### ISSUE TITLE
Scrap config breaks the game

### ISSUE THREAD

**Issue by VanilaBOI** [BananaPuncher714/LethalQuantities#34] opened 2024-01-17 18:22 UTC
When I have the Scrap config enabled/change the max/min scrap value, the game starts and runs fine, until I land on a moon where I edited the scrap config and it just gets stuck at "waiting for crew..".

**Comment by BananaPuncher714** [comment] 2024-01-17 22:12
Can you list the mods you are using, or provide a profile code? And, are you only changing the min/max scrap amounts?

**Comment by VanilaBOI** [comment] 2024-01-17 22:26
Well I am just changing the min/max values but when I tried to only generate the default/empty scrap config of a Moon, it also doesnt land the ship.
018d1988-908f-e05a-1344-7aa63df212f9

**Comment by BananaPuncher714** [comment] 2024-01-17 23:22
I'm not sure what sort of problems there are. I downloaded your profile code, I enabled the scrap config in the global Configuration.cfg for experimentation, then changed the min scrap amount to 5, and the max scrap amount to 20. Experimentation loaded in just fine without getting stuck.

Can you provide a list of steps to replicate this issue, and possibly any errors in the console, if there are any?

**Comment by VanilaBOI** [comment] 2024-01-18 08:54
That's the thing experimentation works but vow or assurance doesn't
Well what I did is configured the monsters and scrap to my liking and realized it didn't work.
So I deleted the whole config and it worked.
Then I did trial and error and tested all settings and ended up realizing that even enabling scrap on a moon in the global config makes it break

**Comment by BananaPuncher714** [comment] 2024-01-18 19:34
Ok, this seems like a duplicate of #30

**Closed** 2024-01-18 23:05 UTC
Labels: bug
